# Generated by Django 6.0.1 on 2026-02-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_icon', models.CharField(max_length=70)),
                ('service_product', models.CharField(max_length=70)),
                ('Sericce_product_description', models.TextField()),
            ],
        ),
    ]
